-- Marketing Analytics Schema (SQLite)
-- ===================================

CREATE TABLE customers (
  ID INTEGER PRIMARY KEY,
  Year_Birth INTEGER,
  Education TEXT,
  Marital_Status TEXT,
  Income REAL,
  Kidhome INTEGER,
  Teenhome INTEGER,
  Country TEXT,
  Dt_Customer TEXT,   -- stored as TEXT, convert in Python if needed
  Recency INTEGER,
  MntWines REAL,
  MntFruits REAL,
  MntMeatProducts REAL,
  MntFishProducts REAL,
  MntSweetProducts REAL,
  MntGoldProds REAL,
  NumDealsPurchases INTEGER,
  NumWebPurchases INTEGER,
  NumCatalogPurchases INTEGER,
  NumStorePurchases INTEGER,
  NumWebVisitsMonth INTEGER,
  AcceptedCmp1 INTEGER,
  AcceptedCmp2 INTEGER,
  AcceptedCmp3 INTEGER,
  AcceptedCmp4 INTEGER,
  AcceptedCmp5 INTEGER,
  Response INTEGER,
  Complain INTEGER,
  Age INTEGER,
  Children INTEGER,
  Total_Spend REAL,
  Total_Purchases INTEGER,
  Customer_Tenure_Days INTEGER,
  Age_Band TEXT,
  Income_Band TEXT,
  Seg_High_Income INTEGER,
  Seg_Young INTEGER,
  Seg_Responder INTEGER,
  Seg_High_Web INTEGER,
  Seg_Family INTEGER,
  Seg_High_Spender INTEGER
);